### ISSUE TITLE
Validate fully qualified domain names

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/tsurlfilter#106]
e.g. `$domain=rarbgto.org.` is considered as invalid now but it shouldn't

https://en.wikipedia.org/wiki/Fully_qualified_domain_name

**Comment by ameshkov** [comment]
Why do we need support fqdns here? It is typical for DNS to deal with them, but to be honest I don't see the reason for that in tsurlfilter or CoreLibs.
