### ISSUE TITLE
Typescript Import issue with NodeNext

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/tsurlfilter#119]
### Summary
AGTree npm package cannot be imported if a developer want to develop new TS program with NodeNext. 

### How to reproduce
[Screencast from 2024-02-28 02-00-15.webm](https://github.com/AdguardTeam/tsurlfilter/assets/98787049/2ca31eb2-3c03-430d-9a4e-381fca2fa88c)

1. Create new TS project.
2. Add `module` and `moduleResolution` key and `NodeNext` value in `tsconfig.json` file.

### Related issue
 - https://github.com/intlify/vue-i18n-next/issues/1327

**Comment by piquark6046** [comment]
I think that using [zod](https://www.npmjs.com/package/zod) instead of superstruct is better option for NodeNext.

**Comment by scripthunter7** [comment]
@piquark6046 It seems already fixed in https://github.com/AdguardTeam/tsurlfilter/commit/fafeda8c09ea61af5680040bfa3e034dee3489de

But we need to make a new release to make it live

**Comment by piquark6046** [comment]
By the way, I suggest [pkgroll](https://github.com/privatenumber/pkgroll) for a zero-config bundler.
