### ISSUE TITLE
Consider to disable `Hide Referer from third parties` (until `$stealth` modifier will be supported) or check if it is possible to disable rules for some websites

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/tsurlfilter#134]
Currently `$stealth` modifier is not supported in MV3 extension, so breakage caused by `Hide Referer from third parties` cannot be fixed in filters.
Consider to disable it or check if it is possible to disable rules for some websites.

For all examples enable `Tracking protection` and `Hide Referer from third parties`.

Few examples:
- https://github.com/AdguardTeam/AdguardFilters/issues/179208
To reproduce:
 I. Go to - https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.icloud.com%2F
 II. Click on the `Sign In` button and then on the `Create Apple ID`
 <details><summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/4eeb125c-89f1-4454-992d-003fb0a8ceab)

![image](https://github.com/user-attachments/assets/8435a580-8d52-43fa-91a8-5a13f1d93db9)

 </details>

- https://github.com/AdguardTeam/AdguardFilters/issues/184831
 I. Go to - https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmapy.cz%2F
  Map doesn't load
 <details><summary>Screenshot</summary>

 ![image](https://github.com/user-attachments/assets/e6b720f5-6442-4a3a-a679-b928eb3bb28f)

 </details>
  
 - NSFW - https://github.com/AdguardTeam/AdguardFilters/issues/182853
  I. Go to - https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmens1069.com%2Farchives%2F325090
  II. Scroll down to the video player
  Video player doesn't load
 <details><summary>Screenshot</summary>

 ![image](https://github.com/user-attachments/assets/bb42d833-8ca5-48c8-bac9-6b8b7216ad8b)

 </details>

**Comment by zloyden** [comment]
Another case https://github.com/AdguardTeam/AdguardFilters/issues/185126.
For some reason, images from `tile.rcs-rds.ro` are not loading because of the enabled `Hide Referer from third parties`. That's not normal behaviour, as the site works fine with the same option in the app or mv2 extension.
