### ISSUE TITLE
Allow to apply $removeparam rules to all resources

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/tsurlfilter#16]
This modifier may be used also for ad blocking(and for removing paramenets from unblocked requests).
Sample our rules:
`||vcms-api*.starlight.digital/hls/*?file=*&testadv=$removeparam=testadv`
`||api.discovery.com/v*/streaming/video/*&adNetworkId$removeparam=/^ad/,domain=hgtv.com`
uBO has similar rules for different sites(`$removeparam` can be used with conent-type modifiers)

Same for CoreLibs and filters compiler validation.

**Comment by ameshkov** [comment]
I suppose we should only allow it to target other content types if the rule has an explicit content-type modifier.
