### ISSUE TITLE
Convert $doc modifier to $document

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/tsurlfilter#2]
At the moment rules with `$doc` are marked as invalid and not converted.
For example - https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_249_NorwegianList/diff.txt#L637
```
Error: "Unknown modifier: doc" in the rule: "||minfodboldbutik.com^$doc"
||minfodboldbutik.com^$doc
```

**Comment by ameshkov** [comment]
@Mizzick 

Once this is done, we should create additional issues:

* CoreLibs
* FiltersCompiler (start using the new tsurlfilter version)
* SafariConverterLib
* https://github.com/ameshkov/VscodeAdblockSyntax
