### ISSUE TITLE
Find out why tsurlfilter results differ from ubo and adblockplus

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/tsurlfilter#28]
See here:
https://github.com/cliqz-oss/adblocker/discussions/2114

Results of adblockplus and ubo should be used as a reference.

**Comment by Mizzick** [comment]
all the rules should be converted first,

```
const converted = TSUrlFilter.RuleConverter.convertRules(loadedRulesText.join('\n')).split('\n');
```

**Comment by ameshkov** [comment]
That's the only issue?
