### ISSUE TITLE
Tracking parameters are not removed on twitter.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/tsurlfilter#34]
@zubrRB commented on [Tue Aug 31 2021](https://github.com/AdguardTeam/AdguardFilters/issues/93136)

А чего не удаляются отслеживающие параметры при переходе по клику с новостного сайта?
https://twitter.com/NickKozlovich/status/1432665253700046850?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1432665253700046850%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Feuroradio.fm%2Fru%2Fu-onlinerby-budet-novyy-glavnyy-redaktor

---

The rules, which must remove parameters:
```
||twitter.com^$removeparam=ref_src
||twitter.com^$removeparam=ref_url
```

**Comment by antoine-hnkx** [comment]
@Alex-302 This is still an issue on Adguard Chrome Extension v4.1.39.

I'm a bit confused on this issue's `Resolution`, is it `Won't Fix` or `Done` ?

I tried to add `||twitter.com^$removeparam=ref_src` and `||twitter.com^$removeparam=ref_url` to my user rules list but that doesn't work either.

Also, I noticed if I force disable and re-enable the extension via the extension ON/OFF button on a twitter URL with `ref_src` and/or `ref_url` it will correctly remove the tracking parameters. This means the rules are indeed activated but they are not triggered for twitter URLs. Other URLs (not from twitter) are working as expected (the tracking params are removed).

You can test with these URLs for convenience:
- Params `ref_src` and `ref_url` not removed. (But removed if disabled and re-enabled the extension with ON/OFF button)
`https://twitter.com/Twitter/status/1564694842311049217?ref_src=test&ref_url=test`
- Param `tuid` is removed as per `||microsoft.com^$removeparam=tduid`.
`microsoft.com?tuid=test`

**Comment by maximtop** [comment]
This issue won't be fixed because these requests are intercepted by service workers and they are not fired in the web request API used to intercept and redirect them.
Here is the corresponding won't fix chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=897060#c41
