### ISSUE TITLE
The unexpected logic of DnsEngine. Impossible to match host rules.

### ISSUE THREAD

**Issue by demian-parkhomenko** [AdguardTeam/tsurlfilter#48]
![image](https://user-images.githubusercontent.com/95881717/160118631-19b256ca-8334-4a4e-aebe-22a906e3bd4b.png)

1) Why the first return statement is needed? If at least one network rule matches in rule storage, all host rules don't. Moreover, unexpected things like `$app `modifier will cause this behavior. Look AdguardTeam/tsurlfilter/issues/47
2) `^$third-party` don't match as a basic rule.

Suggest checking all host rules and `^$third-party` too.  Return both network and host rules.

For matching network rules:
```
//* blah.dummy for matching $third-party rules.
const request = new Request(
    hostname,
    "blah.dummy",
    RequestType.Document 
  );
  request.isHostnameRequest = true;
  networkEngine.hostnameLookupTable.matchAll(request);
```

**Comment by Mizzick** [comment]
> Why the first return statement is needed?
```
/**
 * DNSEngine combines host rules and network rules and is supposed to quickly find
 * matching rules for hostnames.
 * First, it looks over network rules and returns first rule found.
 * Then, if nothing found, it looks up the host rules.
 */
 ```
 
 Actually the key-point is that `networkEngine` in `DnsEngine` should contain only "host-level" network rules, those have higher priority than host rules.

**Comment by Mizzick** [comment]
> ^$third-party don't match as a basic rule.
And it's not supposed to. Please check the logic in this example
https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/examples/manifest-v2/extension/src/background/application.js
Basically there are two instances of engines.
At first `dnsEngine` is used to quickly match among host rules, and then the request is matched in `networkEngine`.

**Comment by demian-parkhomenko** [comment]
Ok, thank you. @Mizzick could you help me? Is it possible to match all "host-level" network and host rules for a hostname?

**Comment by Mizzick** [comment]
@demian-parkhomenko 
Currently there isn't any possibility of this.  Any host-level network rule ($important for instance) has higher priority, so  there is no point to match among host-rules, if network rule is found.

As an option, you might try to filter host-rules and use `dnsEngine` only with them. 

You are always welcome to contribute if you need `matchAll()`,`matchHostRules()` or something like that.

**Comment by demian-parkhomenko** [comment]
@Mizzick what is the best way to match all  “host-level” network rules for a hostname?
