### ISSUE TITLE
$redirect-rule modifier does not work as expected

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/tsurlfilter#51]
See the issue here:
https://github.com/bogachenko/fuckfuckadblock/issues/308#issuecomment-1124923679

In theory since there's a valid blocking rule for the resource, the `redirect-rule` should've been applied.
However, it's not.

Note that the website does not send that request anymore so we should try to reproduce it ourselves.
It also makes sense to add a test case to testcases.adguard.com.

See the `$redirect-rule` documentation here:
https://kb.adguard.com/en/general/how-to-create-your-own-ad-filters#redirect-rule-modifier

**Comment by bogachenko** [comment]
New test link `https://www.zivinice-carsija.com/`
choose any https://github.com/bogachenko/fuckfuckadblock/blob/08e43ec0a709d0f8e7e122cbcb7a263b0e549e58/fuckfuckadblock.txt#L1050
