### ISSUE TITLE
Rule don't match in DnsEngine.

### ISSUE THREAD

**Issue by Blakhard** [AdguardTeam/tsurlfilter#53]
I have an DnsEngine with one rule:

rules: `['|gateway.fe.apple-dns.net^$dnsrewrite=NOERROR;A;149.154.167.99']`

When I trying to match domain `gateway.fe.apple-dns.net` - it does not match.

`const rule = engine.match(domain);`
```
// rule.basicRule = null
// rile.hostRules = []
```

**Comment by maximtop** [comment]
already works in 1.0.3
