### ISSUE TITLE
Add empty $path for just the main page

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/tsurlfilter#54]
See here https://github.com/AdguardTeam/CoreLibs/issues/1591

**Comment by XX-J** [comment]
Добавленный пустой `path` работает некорректно.

 Для примера возьмём яндекс. Мой указатель на главную страницу выглядит следующим образом: `[$domain=yandex.*,path=/^(\/(\[?&\]\[^/\]*)?)?$/]##.desk-notif-card_animated_yes`. Он срабатывает на главной как с завершающим слэшем, так и без оного; как с доп. параметрами после завершающего слэша, так и без них.

 Когда переходишь на [https://yandex.com](https://href.li/?https://yandex.com) из русскоязычного сегмента интернета адрес меняется на [https://yandex.ru/?com=1](https://href.li/?https://yandex.ru/?com=1) (отличается от адреса без параметров наличием ссылки на yandex.com в правой, верхней части страницы), а потом окончание адреса `/?com=1` пропадает.

 В вышеизложенном примере правило `[$domain=yandex.*,path=/^(\/(\[?&\]\[^/\]*)?)?$/]##.desk-notif-card_animated_yes` - срабатывает, скрывая справа анимированную плашку статистики по Коронавирусу, а правило `[$domain=yandex.*,path]##.desk-notif-card_animated_yes` - нет (только после перезагрузки страницы).
<br>

----------
 AdGuard v4.1.1 &nbsp; | &nbsp; FireFox v78.13 ESR &nbsp; | &nbsp; Win7SP1

**Comment by stanislav-atr** [comment]
@XX-J, добрый день! Смена урла с [https://yandex.ru/?com=1](https://href.li/?https://yandex.ru/?com=1) на [https://yandex.ru/](https://href.li/?https://yandex.ru/) происходит без перезагруки и отправления нового запроса, поэтому `yandex.ru/` не может быть сматчен в данном кейсе.

**Comment by XX-J** [comment]
@stanislav-atr, добрый. С параметром на конце или нет, но это всё равно - **главная**. А на любой **заглавной странице** пустой `path` должен работать, т.к. путь **отсутствует**.
