### ISSUE TITLE
Element hiding rule is not applied to all subdomains

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/tsurlfilter#57]
https://www.city.toyota.aichi.jp/
`aichi.jp###sad` - does not hide a banner at the bottom
`toyota.aichi.jp###sad` - hides

AdGuard 4.0.204
Chrome 103.0.5060.134 (64-bit)

**Note:** before checking diable Japanese or all filters.

**Comment by stanislav-atr** [comment]
Looks like a url parser bug to me, i've filed issue [here](https://github.com/remusao/tldts/issues/1389).
