### ISSUE TITLE
Add regexp support for the `$domain` modifier

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/tsurlfilter#58]
See for details: https://github.com/AdguardTeam/CoreLibs/issues/1550

Compatibility info should also be updated, like here: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1109

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/tsurlfilter/issues/41
 https://github.com/AdguardTeam/tsurlfilter/issues/58
 https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1109

**Comment by maximtop** [comment]
Duplicates https://github.com/AdguardTeam/tsurlfilter/issues/41

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AGLint/issues/161
