### ISSUE TITLE
Handle uBO's syntax '$redirect' priorities

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/tsurlfilter#59]
See here for details: https://github.com/AdguardTeam/CoreLibs/issues/1605

**Comment by sxgunchenko** [comment]
Compatibility info should also be updated, like here: https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/1110

**Comment by stanislav-atr** [comment]
Starting with scriptlets version 1.10, UBO's redirect priorities will be silently ignored for AdGuard browser extensions.
