### ISSUE TITLE
Object request type can not be redirected by specifying request type

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/tsurlfilter#61]
URL: `https://gamingsym.in/jp/%e5%8b%95%e7%89%a9%e3%81%af%e3%80%81%e5%9c%b0%e9%9d%a2%e3%81%a8%e7%a9%ba%e6%b0%97%e3%82%92%e4%ba%a4%e4%ba%92%e3%81%ab%e5%97%85%e3%81%90%e6%88%a6%e7%95%a5%e3%82%92%e4%bd%bf%e7%94%a8%e3%81%97%e3%81%a6-2/` (an example, any site with ai_front anti-adb can be used)

Issue: You can't redirect object request (for example, `media.net/dmedianet.js`) by specifying its type e.g. `||media.net/dmedianet.js$object,redirect=noopjs` or `||media.net/dmedianet.js$media,redirect=noopjs` (as AG logs show as media type) fails while unspecified `||media.net/dmedianet.js$redirect=noopjs` suceeds. Also I guess logs should show them as object and not media, maybe.

**Comment by ameshkov** [comment]
Hm, frankly, I thought we should've deprecate $object request type.


How can I see this request? I've opened that page without AG but I don't see it

**Comment by Yuki2718** [comment]
@ameshkov Apparently the site removed anti-adb. Try `celeb.nude.com` [NSFW].

**Comment by AdamWr** [comment]
If I'm not wrong, it should be also possible to reproduce it here - https://jsfiddle.net/7herkmxo/

```html
<object id="ai-adb-mn" data="//contextual.media.net/dmedianet.js" style="position:absolute; z-index: -100; 1px; top: -1000px; left: -1000px; visibility: hidden;"></object>
```
