### ISSUE TITLE
Discard adblock agent properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/tsurlfilter#62]
@ameshkov commented on [Tue Sep 06 2022](https://github.com/AdguardTeam/CoreLibs/issues/1667)

Currently, we only discard `[Adblock`, we should discard more:
`[AdBlock], [Adblock Plus], [uBlock] / [uBlock Origin], [AdGuard]`

See there for the details:
https://github.com/github/linguist/blob/bf853f1c663903e3ee35935189760191f1c45e1c/lib/linguist/heuristics.yml#L681-L700

**Comment by scripthunter7** [comment]
Related https://github.com/AdguardTeam/FiltersCompiler/pull/154
