### ISSUE TITLE
Support :not(:matches-path()) conversion

### ISSUE THREAD

**Issue by maximtop** [AdguardTeam/tsurlfilter#78]
Linked issue is here https://github.com/AdguardTeam/CoreLibs/issues/1725

**Comment by stanislav-atr** [comment]
This was already done as part of https://github.com/AdguardTeam/tsurlfilter/issues/30, yes, for example, rule `ya.ru##:not(:matches-path(/\/(sub1|sub2)\/page\.html/))p` is being converted into `[$path=/^((?!\\/(sub1|sub2)\\/page\\.html).)*$/]ya.ru##p`
