### ISSUE TITLE
Support uBO's matches-media

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/tsurlfilter#81]
Inverse of https://github.com/AdguardTeam/FiltersCompiler/issues/175

**Comment by ameshkov** [comment]
@maximtop possible implementations:

1. Support it uBO-like, i.e. natively (parse the rule, check if there's `:matches-media`, take it into account when composing a rule).
2. Via rules converter

Tbh, I am not sure which one is better.

Also, we should definitely file it to CoreLibs as well.

**Comment by ameshkov** [comment]
Appears to be duplicate of https://github.com/AdguardTeam/tsurlfilter/issues/70
