### ISSUE TITLE
Exception rules interfere with each other

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/tsurlfilter#82]
There are two rules in the Basic Filter (from EL) that don't work together:

`@@||www.google.*/search?$generichide`

`@@||www.google.*/search?$domain=google.ae|google.at|google.be|google.bg|google.by|google.ca|google.ch|google.cl|google.co.id|google.co.il|google.co.in|google.co.jp|google.co.ke|google.co.kr|google. co.nz|google.co.th|google.co.uk|google.co.ve|google.co.za|google.com|google.com.ar|google.com.au|google.com.br|google.com.co|google.com.ec|google.com.eg|google.com.hk|google.com.mx|google.com my|google.com.pe|google.com.ph|google.com.pk|google.com.py|google.com.sa|google.com.sg|google.com.tr|google.com.tw|google.com.ua|google.com.uy|google.com.vn|google.cz|google.de|google.dk|google. dz|google.ee|google.es|google.fi|google.fr|google.gr|google.hr|google.hu|google.it|google.lt|google.lv|google.nl|google.no|google.pl|google.pt|google.ro|google.rs|google.ru|google.se|google.sk`

because of this rule : `~hatena.ne.jp##a[href*="//b.hatena.ne.jp/entry/"]` links in google search results are hidden.

<details><summary>Screenshot:</summary>

https://www.google.com/search?q=inurl%3Ab.hatena.ne.jp%2Fentry

<img width="1020" alt="Screenshot 2023-04-12 at 17 09 15" src="https://user-images.githubusercontent.com/91964807/231483926-95ed7731-8885-4af2-aa70-1d7a00341775.png">

</details><br/>

Expected behavior: links are not hidden

<details><summary>Screenshot:</summary>

<img width="1125" alt="Screenshot 2023-04-12 at 17 10 45" src="https://user-images.githubusercontent.com/91964807/231484317-42b92632-ab6e-4b49-8d3e-b62c6b157406.png">

</details><br/>

When I disable one of the rules, the links appear.

**Comment by ameshkov** [comment]
Do we have the same issue in CoreLibs?

**Comment by jellizaveta** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1749 - yap, created

**Comment by ameshkov** [comment]
In tsurlfilter there's a simple rule of calculating rules priorities: the more "specific" the rule is, the higher the priority is:
https://github.com/AdguardTeam/tsurlfilter/blob/28a011501312f74559a0bc5c7618be9a6f8d2cf8/packages/tsurlfilter/src/rules/network-rule.ts#L825

We already have logic for higher priority of document-level rules:
https://github.com/AdguardTeam/tsurlfilter/blob/master/packages/tsurlfilter/src/rules/network-rule.ts#L763

However, missed `generichide / genericblock` there.

**Comment by 105th** [comment]
@jellizaveta looks like it was fixed with new priority schema. i checked in 4.2.249 - links are visible
<img width="649" alt="Снимок экрана 2024-01-10 в 17 40 42" src="https://github.com/AdguardTeam/tsurlfilter/assets/11395678/e4a4ec69-5a35-4709-88c1-403ef00d77cd">
<img width="835" alt="Снимок экрана 2024-01-10 в 17 40 38" src="https://github.com/AdguardTeam/tsurlfilter/assets/11395678/41cf0379-4aa9-45cb-a98b-3d80be2705b8">
